CAMERA_INDEX = 0
FRAME_AVERAGE_COUNT = 2

# depth camera requires cropping of output
CAMERA_CROP_MODE = "left_half"
CAMERA_FLIP_CODE = -1

SCANLINE_RATIOS = (0.20, 0.42, 0.64)
SCANLINE_WEIGHTS = (0.50, 0.30, 0.20)

MIN_TAPE_RUN_WIDTH_PX = 6
SCANLINE_BAND_HEIGHT_PX = 9
DEFAULT_LANE_WIDTH_RATIO = 0.40
MIN_LANE_WIDTH_RATIO = 0.18
MAX_LANE_WIDTH_RATIO = 0.92

VISION_SMOOTHING_FRAMES = 4

RIGHT_P_DIFF = 0
LEFT_p_DIFF = 0

# mc left
PIN_ENA = 32
PIN_IN1 = 35
PIN_IN2 = 37

# mc right
PIN_ENB = 33
PIN_IN3 = 36
PIN_IN4 = 38