CAMERA_INDEX = 0
FRAME_AVERAGE_COUNT = 1

# depth camera requires cropping of output
CAMERA_CROP_MODE = "left_half"
CAMERA_FLIP_CODE = -1

SCANLINE_RATIOS = (0.11, 0.33, 0.55, 0.77)
SCANLINE_WEIGHTS = (0.15, 0.15, 0.50, 0.20)

MIN_TAPE_RUN_WIDTH_PX = 6
SCANLINE_BAND_HEIGHT_PX = 9
DEFAULT_LANE_WIDTH_RATIO = 0.40
MIN_LANE_WIDTH_RATIO = 0.18
MAX_LANE_WIDTH_RATIO = 0.92

VISION_SMOOTHING_FRAMES = 4

TURNING_TRIGGER_OFFSET = 0.10
MOTOR_TURN_GAIN = 1.25

VIDEO_OUTPUT_DIR = "recordings"
VIDEO_FPS = 20
VIDEO_SEGMENT_SECONDS = 10
VIDEO_FOURCC = "MJPG"
VIDEO_EXTENSION = ".avi"

RIGHT_P_DIFF = 0
LEFT_p_DIFF = 0

# mc left
PIN_ENA = 32
PIN_IN1 = 35
PIN_IN2 = 37

# mc right
PIN_ENB = 33
PIN_IN3 = 36
PIN_IN4 = 38

PIN_BTN = 31
